# models/geminiflash.conf
# Remote Google Flash AI Model configuration
SELECTED_MODEL_MAX_CHARACTERS="4000000"    # Economy setting in characters with token base size of 4
SELECTED_MODEL_NAME="gemini-3-flash-preview" 
SELECTED_CONTEXT_SIZE="1048000"
SELECTED_MODEL_RETRY_TIMEOUT=30
SELECTED_MODEL_BASE_URL="https://generativelanguage.googleapis.com/v1beta/models/${SELECTED_MODEL_NAME}:generateContent"
GEMINI_API_KEY=""