# models/geminiflash.conf
# Remote Google Flash AI Model configuration
MODEL_MAX_CHARACTERS="4000000"    # Economy setting in characters with token base size of 4
MODEL_NAME="gemini-3-flash-preview" 
MODEL_CONTEXT_SIZE="1048000"
MODEL_RETRY_TIMEOUT=60
MODEL_BASE_URL="https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent"
API_KEY=""