# models/googleapi.conf
# Remote AI Model configuration
MODEL_MAX_CHARACTERS="4000000"    # Economy setting in characters with token base size of 4
MODEL_NAME="gemini-3-flash-preview"
MODEL_CONTEXT_SIZE="1048000"
MODEL_RETRY_TIMEOUT=30
API_KEY=""