# models/local.conf
# Local Ollama AI Model configuration
MODEL_MAX_CHARACTERS="4000000"    # Economy setting in characters with token base size of 4
MODEL_NAME="qwen-fixed:latest"
MODEL_CONTEXT_SIZE="16384"
MODEL_RETRY_TIMEOUT=600
MODEL_BASE_URL=""