# models/openrouter.conf
# Remote OpenRouter AI Model configuration
MODEL_MAX_CHARACTERS="4000000"    # Economy setting in characters with token base size of 4
MODEL_NAME="~openai/gpt-latest"
MODEL_CONTEXT_SIZE="1000000"
MODEL_RETRY_TIMEOUT=10
MODEL_BASE_URL="https://openrouter.ai/api/v1/chat/completions"
SITE_URL="mysite.com"
SITE_TITLE="mysite"
API_KEY=""